### PR TITLE
Remove default of zero from Bools, add predicate

### PR DESCRIPTION
**Pull request by mateu**

### CODE REVIEW

**Comment by autarch** [comment]
This needs a doc update.

**Comment by oschwald** [comment]
Ah, right.

**Comment by oschwald** [comment]
Do we document any of the predicate methods?

**Comment by andyjack** [comment]
In WS::MF::Client there is "Every record class attribute has a corresponding predicate method so that you can check to see if the attribute is set."  It's buried at the bottom in "What Data Is Returned?" though.

**Comment by autarch** [comment]
The `predicate => 1` thing creates a _public_ predicate method for public attributes, so we need to document it. If these aren't intended for public use, then we need to write out `predicate => '_has_public_attr'`

**Pull request merged**
